// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using todo_rest_api;

namespace todo_rest_api.Migrations
{
    [DbContext(typeof(TodoListContext))]
    [Migration("20211104133407_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("todo_rest_api.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean")
                        .HasColumnName("done");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<int>("ListId")
                        .HasColumnType("integer")
                        .HasColumnName("list_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TodoListId")
                        .HasColumnType("integer")
                        .HasColumnName("todo_list_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("TodoListId")
                        .HasDatabaseName("ix_tasks_todo_list_id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("todo_rest_api.Models.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.HasKey("Id")
                        .HasName("pk_lists");

                    b.ToTable("lists");
                });

            modelBuilder.Entity("todo_rest_api.Models.TodoItem", b =>
                {
                    b.HasOne("todo_rest_api.Models.TodoList", "TodoList")
                        .WithMany("TaskList")
                        .HasForeignKey("TodoListId")
                        .HasConstraintName("fk_tasks_lists_todo_list_id");

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("todo_rest_api.Models.TodoList", b =>
                {
                    b.Navigation("TaskList");
                });
#pragma warning restore 612, 618
        }
    }
}
